# **Online Advertising Performance Marketing**

## Objectives

* I have used the Online Advertising Performance Dataset again because I believe I can present the visual data clearly in Tableau or Power BI. As the task in this unit is to clean the data, present our findings and make notes as I go along.

* I will also include a Machine Learning algorithm to either present the discovered data or possibly make a prediction.

## Inputs & Outputs

* This time not only have I asked Chatgpt and Copliot to fix or generate codes, but I have commented in the sections of the markdowns what I wanted the output to be, Copilot has read it and has predicted the codes used to get the results.

* Cleaning the data was interesting as I only commented "#clean Data" and remove two unnamed coloumns. This was very useful because in the first iteration in Tableau of the dataset, I seen coloumns called "F1" to "F25", I realised that the data needed cleaning and removing those coloumns. It's safe to assume they had some value, just not reliable data for what I wanted to present.

* Thanks to commenting in the code dropdowns, I was able to generate a more accurate line and pie chart, which required some removing and including data which I valued and remembered the task is Customer/User Engagment. 

## Additional Comments

I have used the Online Advertising Perfomance Data created by N. Aniruddhan from Kaggle.

I have also Credited N. Aniruddhan in the description of the dataset in Tableau.

---

# Work directory

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\PC\\Documents\\vs_code\\Unit2_resub_Online_Advertising\\Unit2_Resub_Online_Advertising_Performance\\jupyter_notebooks'

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\PC\\Documents\\vs_code\\Unit2_resub_Online_Advertising\\Unit2_Resub_Online_Advertising_Performance'

# Section 1

Imports & Machine Learning algorithms.

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Import after installation
import sklearn
print(sklearn.__version__)

1.9.1

In [6]:
sklearn_version = sklearn.__version__
print(f"Scikit-learn version: {sklearn_version}")

Scikit-learn version: 1.9.1

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error

# Machine Learning Algorthims

These are the types of learning for AI and what they are commonly used for.

* Supervised = The AI learns from examples that are already correct and known.

Used for: Predicting house prices, detecting spam, forecasting sales.

* Unsupervised = AI discovers groups, relathionships and structures without being given the correct answer.

Used for: Customer segmentation, anomaly detection, discovering patterns in datasets.

* Reinforcement = AI takes action, revises their conseuence and re-evaluates with a strategy to gain a reward. 

Used for: Robotics, game-playing, resource allocation, control systems.

* Semi-Supervised = AI learns from a small set of labelled examples and larger sets of unlabelled examples.

Used for: Image classification, speech recognition, medical image analysis.

* Self-Supervised = AI generates it's own targets from the input data rather than human/user interaction.

Used for: Large language models, image understanding, speech processing.

After asking Chatgpt for the ML (Machine Learning) types, it has also asked me if I wanted a suggestion. I know with the dataset I have chosen I'm aiming towards a predictive outcome/algorithm because I think it would be interesting to see how the campaigns WOULD have been in an extra month or two.

Chatgpt Recommends:
* Linear Regression 
* Random Forest Regressor
* Gradient boosting: XGBoost, LightGBM, CatBoost
* Ridge & Lasso Regression
* K-Nearest Neighbours Regression (KNN)

---

# Section 2

Loading the dataset, investigating Campaign 2 and removing missing values.

In [11]:
# read 'online_advertising_performance_data.csv' from the 'datasets' folder
df = pd.read_csv('datasets/online_advertising_performance_data.csv')
df.head()

,month,day,campaign_number,user_engagement,banner,placement,displays,cost,clicks,revenue,post_click_conversions,post_click_sales_amount,Unnamed: 12,Unnamed: 13
0,April,1,camp 1,High,160 x 600,abc,4,0.0060,0,0.0000,0,0.0000,NaN,NaN
1,April,1,camp 1,High,160 x 600,def,20170,26.7824,158,28.9717,23,1972.4602,NaN,NaN
2,April,1,camp 1,High,160 x 600,ghi,14701,27.6304,158,28.9771,78,2497.2636,NaN,NaN
3,April,1,camp 1,High,160 x 600,mno,171259,216.8750,1796,329.4518,617,24625.3234,NaN,NaN
4,April,1,camp 1,Low,160 x 600,def,552,0.0670,1,0.1834,0,0.0000,NaN,NaN

As I know already this is the same dataset/csv file from the previous unit. I can see Unnamed 12 & 13 with missing values, But I still wonder if Campaign 2 has any values or documentation after April?

Thinking ahead, I asked Chatgpt to inspect and clean the dataset for any Duplicates, Missing Values and reoprt any edits or findings.

In [12]:
# from datasets folder, read 'OAP_CGPT_data_cleaned.csv'
df = pd.read_csv('datasets/OAP_CGPT_data_cleaned.csv')
df.head()

,month,day,campaign_number,user_engagement,banner,placement,displays,cost,clicks,revenue,post_click_conversions,post_click_sales_amount
0,April,1,camp 1,High,160 x 600,abc,4,0.0060,0,0.0000,0,0.0000
1,April,1,camp 1,High,160 x 600,def,20170,26.7824,158,28.9717,23,1972.4602
2,April,1,camp 1,High,160 x 600,ghi,14701,27.6304,158,28.9771,78,2497.2636
3,April,1,camp 1,High,160 x 600,mno,171259,216.8750,1796,329.4518,617,24625.3234
4,April,1,camp 1,Low,160 x 600,def,552,0.0670,1,0.1834,0,0.0000

Chatgpt has removed Unnamed 12 & 13, great. I aslo asked if theres further documentation for Campaign 2 past April, same answer as before except "No, The cleaned CSV contains no documentation for Campaign 2 beyond April." 

In the Data Wrangler I can see 'camp 2'. My thoughts are now 'Do I make a prediction for Camp 2 when there's no further information to possibly predict, even past April from the original dataset?' and for the sake of a business enquiry 'Do I present Campaigns 1 & 3 with their prediction of an extra month (Or two)?

In [13]:
# read from 'datasets' folder, 'OAP_CGPT_data_without_camp2.csv'
df = pd.read_csv('datasets/OAP_CGPT_data_without_camp2.csv')
df.head()

,month,day,campaign_number,user_engagement,banner,placement,displays,cost,clicks,revenue,post_click_conversions,post_click_sales_amount
0,April,1,camp 1,High,160 x 600,abc,4,0.0060,0,0.0000,0,0.0000
1,April,1,camp 1,High,160 x 600,def,20170,26.7824,158,28.9717,23,1972.4602
2,April,1,camp 1,High,160 x 600,ghi,14701,27.6304,158,28.9771,78,2497.2636
3,April,1,camp 1,High,160 x 600,mno,171259,216.8750,1796,329.4518,617,24625.3234
4,April,1,camp 1,Low,160 x 600,def,552,0.0670,1,0.1834,0,0.0000

I have proceeded without Campaign 2 due to no further information.

Also asking Chatgpt to remove Campaign 2, with a report of changes and accuracy(?). I feel that if I asked/commented Copilot to remove Camp 2, would it just remove the name from the 'campaign_number'?

Having looked again in Data Wrangler, I can see campaigns 1 & 3, the 12 columns that Chatgpt said it HAS NOT removed, Missing & or duplicate Values and unnamed columns have been successfully removed.

---

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.